BoardsXpress/BoardsXpress/BoardsXpress/Models/MeetingAttendeesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BoardsXpress.Models
{
    public class MeetingAttendeesView : GenericErrors
    {

        public List<MeetingAttendeesViewModel> ListMeetings { get; set; }

    }

    public class MeetingAttendeesViewModel
    {
        public string FirstName { get; set; }
        public string UserId { get; set; }
        public bool? UserResponse { get; set; }
    }
}

BoardsXpress/BoardsXpress/BoardsXpress/Controllers/MeetingAttendeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BoardsXpress;

using Microsoft.AspNet.Identity.Owin;
using BoardsXpress.Models;
using Microsoft.AspNet.Identity;
using System.Web.Security;

namespace BoardsXpress.Controllers
{
    [Authorize]

    public class MeetingAttendeesController : Controller
    {
        private BoardExpressEntities db = new BoardExpressEntities();
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: MeetingAttendee
        public ActionResult Index(Guid? id)
        {
            var userInRole = User.IsInRole("Super Admin");
            List<AspNetUser> user = new List<AspNetUser>();
            user = (from x in db.AspNetUsers
                    join y in db.AspNetUserRoles
                    on x.Id equals y.UserId
                    where y.MeetingTypeId == id && x.FirstName != "Super Admin"
                    select x).Distinct().ToList();
            //if (userInRole) //if the user is super admin show her all the users
            //{
            //    //user = (from x in db.AspNetUsers
            //    //        where x.FirstName != "Super Admin"
            //    //        select x).Distinct().ToList();
            //}
            //else
            //{
            //    user = (from x in db.AspNetUsers
            //            join y in db.AspNetUserRoles
            //            on x.Id equals y.UserId
            //            where y.MeetingTypeId == id && x.FirstName != "Super Admin"
            //            select x).Distinct().ToList();
            //}
            //List<ApplicationUser> user = UserManager.Users.Where(w => w.FirstName != "Super Admin").ToList();
            var roleAssignmentList = new List<UserRoleAssignmentViewModels>();
            if (id == null)
            {
                var meetingDateList = GetMeetingsInformations(id.Value);
                var meetingInformations = db.tblMeetings.Where(w => w.meetingType == id.Value).ToList();
                var test = db.AspNetRoles.Where(w => w.Name != "Super Admin").Where(w => w.Name != "Admin").ToList();
                var userList = new List<UserInfoViewModels>();
                foreach (var item in user)
                {
                    var usr = new UserInfoViewModels();
                    usr.FirstName = item.FirstName;
                    usr.UserId = item.Id;
                    usr.userRole = new SelectList(test, "Id", "Name");
                    userList.Add(usr);
                }

                var roleAssignment = new UserRoleAssignmentViewModels();
                roleAssignment.userList = userList;

                roleAssignment.MeetingTypeId = id.Value;

                return View(roleAssignment);
            }
            else
            {

                var userRoles = db.AspNetUserRoles.Where(w => w.MeetingTypeId == id.Value).ToList();

                var list = user.Where(w => userRoles.Any(z => z.UserId == w.Id));
                var roleAssignment = new UserRoleAssignmentViewModels();
                var roleList = db.AspNetRoles.Where(w => w.Name != "Super Admin").Where(w => w.Name != "Admin").ToList();
                var userList = new List<UserInfoViewModels>();
                foreach (var item in user)
                {
                    var usr = new UserInfoViewModels();
                    usr.FirstName = item.FirstName;
                    usr.UserId = item.Id;
                    usr.userRoleSelected = userRoles.Where(w => w.UserId == item.Id).Select(s => s.RoleId).FirstOrDefault();
                    usr.userRole = new SelectList(roleList, "Id", "Name", userRoles.Where(w => w.UserId == item.Id).Select(s => s.RoleId).FirstOrDefault());

                    userList.Add(usr);
                }
                var meetingInformations = db.tblMeetings.Where(w => w.meetingType == id.Value).ToList();

                roleAssignment.userList = userList;

                roleAssignment.MeetingTypeId = id.Value;
                roleAssignment.MeetingType = db.tblMeetingTypes.Where(w => w.meetingTypeId == id.Value).Select(s => s.meetingType).FirstOrDefault();

                return View(roleAssignment);
            }


        }

        public ActionResult Selection(Guid id)
        {

            return RedirectToAction("Index", new
            {
                meetingId = id
            });


        }
        public ActionResult Save(UserRoleAssignmentViewModels UserRoleList)
        {
            ///check if user is already present 
            ///int userrole table before adding 
            ///

            var meetingId = Guid.Empty;
            try
            {
                foreach (var item in UserRoleList.userList.Where(w => w.userRoleSelected != null))
                {
                    var meetingTypeId = UserRoleList.MeetingTypeId;
                    var userId = item.UserId;
                    var selectedRole = item.userRoleSelected;
                    var checkAnotherRole = db.AspNetUserRoles.Where(w => w.UserId == userId).Where(w => w.MeetingTypeId == meetingTypeId);
                    if (checkAnotherRole.Count() == 1)
                    {
                        //delete the previous and add new one
                        var something = (AspNetUserRole)checkAnotherRole.FirstOrDefault();
                        db.AspNetUserRoles.Remove(something);
                        AddToRoleAsync(item.UserId, item.userRoleSelected, meetingId, UserRoleList.MeetingTypeId);
                        //updateCode
                        //update role

                    }


                    var checkRole = db.AspNetUserRoles.Where(w => w.UserId == userId).Where(w => w.MeetingTypeId == meetingTypeId).Where(w => w.RoleId == selectedRole);
                    if (checkRole.Count() == 0)
                    {

                        AddToRoleAsync(item.UserId, item.userRoleSelected, meetingId, UserRoleList.MeetingTypeId);
                    }
                }
                foreach (var item in UserRoleList.userList.Where(w => w.userRoleSelected == null))
                {
                    var userId = item.UserId;
                    var checkRole = db.AspNetUserRoles.Where(w => w.UserId == userId).Where(w => w.MeetingTypeId == UserRoleList.MeetingTypeId).ToList();
                    if (checkRole.Count() == 1)
                    {
                        var something = (AspNetUserRole)checkRole.FirstOrDefault();
                        db.AspNetUserRoles.Remove(something);
                        db.SaveChanges();
                        //delete the user

                    }

                }
                #region Save and Send 
                var isInvite = Request.Form["isInvite"];
                if (isInvite != null)
                {
                    var messageBody = Request.Form["txtMessageBody"];
                    var subject = "Meeting Invite";
                    EmailProviderController oController = new EmailProviderController();
                    List<string> attendees = new List<string>();

                    //get users from the list who are assigned roles;
                    foreach (var item in UserRoleList.userList)
                    {
                        if (!string.IsNullOrEmpty(item.userRoleSelected))
                        {
                            var user =  UserManager.FindByIdAsync(item.UserId);
                            attendees.Add(user.Result.Email);
                        }
                    }



                    oController.sendMail(attendees, subject, messageBody,"Invite");
                }
                #endregion
                return RedirectToAction("Index", new
                {
                    id = UserRoleList.MeetingTypeId
                });


            }
            catch (Exception ex)
            {

                throw;
            }



        }
        [HttpPost]
        public void SaveAndSend()
        {

        }



        public List<SelectListItem> UserRoleList()
        {

            List<SelectListItem> groupList = new List<SelectListItem>();
            var userGroups = db.AspNetRoles.Where(w => w.Name != "Super Admin").Where(w => w.Name != "Admin").ToList();
            foreach (var item in userGroups)
            {
                groupList.Add(new SelectListItem
                {
                    Text = item.Name,
                    Value = item.Id,
                    Selected = false
                });
            }
            return groupList;
        }

        //public SelectList UserRoleList()
        //{

        //    List<SelectListItem> groupList = new List<SelectListItem>();
        //    var userGroups = db.AspNetRoles.Where(w => w.Name != "Super Admin").Where(w => w.Name != "Admin").ToList();
        //    var gList = new SelectList(userGroups, "ID", "NAME");


        //    foreach (var item in userGroups)
        //    {
        //        groupList.Add(new SelectListItem
        //        {
        //            Text = item.Name,
        //            Value = item.Id,
        //            Selected = false
        //        });
        //    }
        //    return gList;
        //}


        public bool AddToRoleAsync(string userId, string role, Guid? meetingId, Guid? meetingTypeId)

BoardsXpress/BoardsXpress/BoardsXpress/Views/MeetingAttendees/Create.cshtml
@model BoardsXpress.tblMeetingAttendee

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tblMeetingAttendee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.meetingId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.meetingId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.meetingId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.groupId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.groupId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.groupId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BoardsXpress/BoardsXpress/BoardsXpress/Views/MeetingAttendees/Delete.cshtml
@model BoardsXpress.tblMeetingAttendee

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tblMeetingAttendee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.meetingId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.meetingId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.groupId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.groupId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BoardsXpress/BoardsXpress/BoardsXpress/Views/MeetingAttendees/Details.cshtml
@model BoardsXpress.tblMeetingAttendee

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>tblMeetingAttendee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.meetingId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.meetingId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.groupId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.groupId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.eventId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BoardsXpress/BoardsXpress/BoardsXpress/Views/MeetingAttendees/Edit.cshtml
@model BoardsXpress.tblMeetingAttendee

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tblMeetingAttendee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.eventId)

        <div class="form-group">
            @Html.LabelFor(model => model.meetingId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.meetingId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.meetingId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.groupId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.groupId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.groupId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BoardsXpress/BoardsXpress/BoardsXpress/Views/MeetingAttendees/Index.cshtml
@model BoardsXpress.Models.UserRoleAssignmentViewModels
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_DashboardSidebar.cshtml";
    //var meetingTypeId = Model.Select(s => s.MeetingTypeId).FirstOrDefault();
    var meetingTypeId = Model.MeetingTypeId;
}

<link rel="stylesheet" href="~/Content/bootstrap-select.min.css" />
<script src="~/Scripts/bootstrap-select.min.js"></script>

<div id="rightdash-container">
    <span class="btn btn-xs btn-default" data-toggle="tooltip" data-original-title="Go back to Meeting Types " data-placement="top" onclick="location.href = '/MeetingAdministration?id=@meetingTypeId'"><< Go Back</span>
    @*Tabs*@
    <h4 style="text-align:center;">Manage Roles for @Model.MeetingType</h4>
    <ul class="nav nav-tabs" id="userManagementTabs">
        <li><a href="/UserManagement?id=@meetingTypeId">Manage Users</a></li>
        <li class="active" id="manage-attendees"><a href="/MeetingAttendees?id=@meetingTypeId">Manage Roles</a></li>

    </ul>
    <div class="tab-content">
        <br />
        @*<button class="btn btn-warning pull-right defaultUserConfig">Set Default</button>*@
        @if (Model != null)
        {
            using (Html.BeginForm("Save", "MeetingAttendees", FormMethod.Post, new { id = "frmSaveRoles" }))
            {
                <table class="table table-striped table-hover table-responsive">
                    <thead>
                        <tr>
                            <th style="display:none">ID</th>
                            <th>Full Name</th>
                            <th>Role</th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int i = 0; i < Model.userList.Count(); i++)
                    {
                            @*@Html.HiddenFor(item=>item.UserId)*@
                            <tr>
                                <td style="display:none">@Html.HiddenFor(m => m.userList[i].UserId)</td>
                                <td style="display:none">@Html.HiddenFor(m => m.MeetingTypeId)</td>
                                <td>@Html.DisplayFor(m => m.userList[i].FirstName)</td>
                                <td>@Html.DropDownListFor(m => m.userList[i].userRoleSelected, Model.userList[i].userRole, "Select", new { @class = "" })</td>
                            </tr>
                        }
                    </tbody>
                </table>
                <input type="submit" class="btn btn-warning pull-right" value="Save" style="margin-left:10px;">
                @*<input type="button" class="btn btn-warning pull-right" value="Save and Send Invitations" id="SaveAndSend">*@
                //create and assign a input type variable for send invite, access from controller(Check) if set, save and invoke
                //send action

                <!--Mail Modal-->
                <div class="modal fade" id="mailModal" tabindex="-1" role="dialog" aria-labelledby="checkModal" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                <h4 class="modal-title" id="checkModal">Invitation to attend</h4>
                            </div>
                            <div class="modal-body">
                                <p id="mailBodyText">
                                    <textarea name="txtMessageBody" style="width:530px;height:200px;">Dear Mr Attendee:&#13 &#13;I am pleased to invite you to participate on our @Model.MeetingType Meeting.&#13;Date: 20/05/17 &#13;Venue: WordFlow Global Headquarters &#13 &#13 Sincerely, &#13 @User.Identity.Name
                                    </textarea>
                                </p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-primary" data-dismiss="send" id="sendInvite">Send</button>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }

    </div>
</div>

<script>
    $(document).ready(function (e) {
        $('.selectpicker').selectpicker({
            style: 'btn-default'
        });
        $('.filter-option').css('color', '#333333');
    });


    $('#SaveAndSend').click(function () {
        $('#mailModal').modal('show');
    });
    $('#sendInvite').click(function () {
        var mailBody = $('#mailBodyText').text();
        $('#frmSaveRoles').append('<input type = "text" name = "isInvite" id = "isInvite" style="Display:none;"/>');
        //$('#isInvite').val(mailBody);
        $('#frmSaveRoles').submit();
    });
</script>