BoardsXpress/BoardsXpress/BoardsXpress/Models/UserManagementViewModels.cs

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BoardsXpress.Models
{
    public class UserManagementViewModels : GenericErrors
    {

        #region aspUser

        public string UserId { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string PhoneNumber { get; set; }
        [DisplayName("FirstName")]
        public string FirstName { get; set; }
        public string Organisation { get; set; }
        public string Designation { get; set; }
        public string Avatar { get; set; }
        public string Password { get; set; }
        public bool SelectedUser { get; set; }
        public string SelectTitle { get; set; }
        #endregion

        public Guid MeetingTypeId { get; set; }
        public string MeetingType { get; set; }
        public Guid MeetingId { get; set; }
        public HttpPostedFileBase ImageUpload { get; set; }

        #region Roles
        // public List<tblUserGroup> UserGroupList { get; set; }
        public List<SelectListItem> UserGroupList { get; set; }
        public List<RoleViewModels> Roles { get; set; }
        public List<MeetingViewModels> Meetings { get; set; }
        public RoleViewModels userInRole { get; set; }
        public string SelectedRoleId { get; set; }
        public Guid AspNetUserRoleId { get; set; }

        public DateTime StartDate { get; set; } = DateTime.Now;
        public DateTime? EndDate { get; set; }

        public string FormatStartDate { get; set; } = DateTime.Now.ToString("dd/MM/yyyy");
        public string FormatEndDate { get; set; }

        public String ExtFormatStartDate
        {
            get
            {
                return EndDate?.ToString("dd/MM/yyyy");
            }
        }
        public String ExtFormatEndDate
        {
            get
            {
                return EndDate != null ? EndDate.Value.ToString("dd/MM/yyyy") : null;
            }
        }

        public bool? UserResponse { get; set; }

        // public string groupName { get; set; }
        #endregion



    }
}

BoardsXpress/BoardsXpress/BoardsXpress/Controllers/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

using BoardsXpress.Models;
using Microsoft.AspNet.Identity.Owin;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using System.IO;
using System.Text.RegularExpressions;
using Newtonsoft.Json;

namespace BoardsXpress.Controllers
{

    [Authorize]
    public class UserManagementController : BaseController
    {
        private bool RoleAddFlag = false;

        #region Constructor

        public UserManagementController() { }

        public UserManagementController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        #endregion

        #region Properties

        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        EmailProviderController oEmailProvider = new EmailProviderController();
        private Guid MeetingTypeId;

        #endregion

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult UserInRoleManagement(Guid id)
        {
            ViewBag.meetingTypeId = id;
            var meetingTypeName = (from x in db.tblMeetingTypes where x.meetingTypeId == id select new { x.meetingType, x.useAbbreviation, x.meetingAbbreviation }).FirstOrDefault();
            ViewBag.meetingTypeName = meetingTypeName.useAbbreviation ? meetingTypeName.meetingAbbreviation : meetingTypeName.meetingType;
            TempData["MeetingTypeId"] = id;
            TempData.Keep("MeetingTypeId");
            return View();
        }


        #region "Ajax call"

        public ActionResult GetUsersList()
        {
            UserRoleAssignmentViewModels userList = new UserRoleAssignmentViewModels();
            userList.userListViewModel = new List<UserManagementViewModels>();
            userList.UserTitle = new List<UserTitleViewModel>();
            userList.TypeOfMember = new List<UserTitleViewModel>();
            try
            {
                userList.userListViewModel = getDbUserList();
                var dbuserTitle = db.tblUserTitles.ToList();
                var dbTypeofMember = db.tblTypeOfmembers.ToList();
                dbuserTitle.ForEach(item =>
                {
                    userList.UserTitle.Add(new UserTitleViewModel
                    {
                        Id = item.Id,
                        Title = item.Title
                    });
                });
                dbTypeofMember.ForEach(item =>
                {
                    userList.TypeOfMember.Add(new UserTitleViewModel
                    {
                        Id = item.Id,
                        Title = item.MemberType
                    });
                });
            }
            catch (Exception ex)
            {
                userList.ErrorCode = ex.HResult;
                userList.ErrorMessage = ex.Message;
            }
            return Json(userList, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetUserRoleList()
        {

            //var meetingType = db.tblMeetingTypes.Where(w => w.meetingTypeId == id).Select(s => s.meetingType).FirstOrDefault().ToString();
            //ViewBag.meetingType = meetingType;
            //MeetingTypeId = id;
            //ViewBag.meetingTypeId = id;
            UserRoleAssignmentViewModels userRoleAssignmentViewModels = new UserRoleAssignmentViewModels();
            try
            {
                userRoleAssignmentViewModels.userListViewModel = new List<UserManagementViewModels>();
                userRoleAssignmentViewModels.userListViewModel = getListOfUserInRole();
            }
            catch (Exception ex)
            {
                userRoleAssignmentViewModels.ErrorMessage = ex.InnerException.Message;
                userRoleAssignmentViewModels.ErrorCode = ex.HResult;

            }


            return Json(userRoleAssignmentViewModels, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetUserRoleAllIndividual(string userId, string roleId)
        {
            var user = (dynamic)null;
            string getRole = null;
            UserRoleAssignmentViewModels userRoleAssignmentViewModels = new UserRoleAssignmentViewModels();
            userRoleAssignmentViewModels.userListViewModel = new List<UserManagementViewModels>();
            List<AspNetRole> roles = new List<AspNetRole>();
            try
            {
                if (!string.IsNullOrWhiteSpace(userId) && !string.IsNullOrWhiteSpace(roleId) && !string.IsNullOrWhiteSpace(TempData.Peek("MeetingTypeId").ToString()))
                {
                    Guid meetingTypeId = new Guid(TempData.Peek("MeetingTypeId").ToString());
                    user = (from u in db.AspNetUsers
                            join ur in db.AspNetUserRoles on u.Id equals ur.UserId
                            where u.Id == userId && ur.RoleId == roleId && ur.MeetingTypeId == meetingTypeId
                            select new
                            {
                                u.Email,
                                u.PhoneNumber,
                                u.Organisation,
                                u.Designation,
                                u.Avatar,
                                u.Title,
                                u.FirstName,
                                ur.RoleId,
                                ur.Id,
                                ur.StartDate,
                                ur.EndDate,
                                ur.MeetingTypeId
                            }).ToList();
                }
                else
                {
                    user = (from x in db.FunctionASPNetUsersRoleList(new Guid(TempData.Peek("MeetingTypeId").ToString())) select x).ToList();
                    getRole = (from r in db.AspNetRoles
                               where r.fullAccess == false && r.readAccess == true && r.writeAccess == true
                               select r.Id).FirstOrDefault();

                }
                roles = (from y in db.AspNetRoles where y.Name != "Super Admin" select y).ToList();
                foreach (var item in user)
                {
                    var UserManagementViewModels = new UserManagementViewModels();
                    UserManagementViewModels.UserId = item.Id.ToString();
                    UserManagementViewModels.AspNetUserRoleId = item.Id is Guid ? item.Id : new Guid(item.Id);
                    UserManagementViewModels.Email = item.Email;
                    UserManagementViewModels.PhoneNumber = item.PhoneNumber;
                    UserManagementViewModels.FirstName = item.FirstName;
                    UserManagementViewModels.Organisation = item.Organisation;
                    UserManagementViewModels.Designation = item.Designation;
                    UserManagementViewModels.Avatar = item.Avatar;
                    UserManagementViewModels.SelectTitle = item.Title;
                    if (!string.IsNullOrWhiteSpace(userId) && !string.IsNullOrWhiteSpace(roleId) && !string.IsNullOrWhiteSpace(TempData.Peek("MeetingTypeId").ToString()))
                    {
                        UserManagementViewModels.userInRole = new RoleViewModels
                        {
                            Id = item.RoleId
                        };
                        UserManagementViewModels.FormatStartDate = item.StartDate == null ? DateTime.Now.ToString("dd/MM/yyyy") : item.StartDate.ToString("dd/MM/yyyy");
                        UserManagementViewModels.FormatEndDate = item.EndDate == null ? null : item.EndDate.ToString("dd/MM/yyyy");
                        UserManagementViewModels.SelectedUser = (!string.IsNullOrWhiteSpace(userId) && !string.IsNullOrWhiteSpace(roleId) && !string.IsNullOrWhiteSpace(TempData.Peek("MeetingTypeId").ToString())) ? true : false;
                    }
                    else
                    {
                        UserManagementViewModels.userInRole = new RoleViewModels();
                    }
                    UserManagementViewModels.SelectedRoleId = (!string.IsNullOrWhiteSpace(userId) && !string.IsNullOrWhiteSpace(roleId) && !string.IsNullOrWhiteSpace(TempData.Peek("MeetingTypeId").ToString())) ? item.RoleId : getRole;
                    UserManagementViewModels.Roles = new List<RoleViewModels>();
                    roles.ForEach(i =>
                    {
                        var role = new RoleViewModels
                        {
                            Id = i.Id,
                            Name = i.Name,
                            Description = i.Description,
                            fullAccess = i.fullAccess,
                            readAccess = i.readAccess,
                            writeAccess = i.writeAccess
                        };

BoardsXpress/BoardsXpress/BoardsXpress/Controllers/UserProfilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BoardsXpress;


namespace BoardsXpress.Controllers
{
    public class UserProfilesController : Controller
    {
        private BoardExpressEntities db = new BoardExpressEntities();

        // GET: UserProfiles
        public ActionResult Index()
        {
            return View(db.tblUserProfiles.ToList());
        }

        // GET: UserProfiles/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblUserProfile tblUserProfile = db.tblUserProfiles.Find(id);
            if (tblUserProfile == null)
            {
                return HttpNotFound();
            }
            return View(tblUserProfile);
        }

        // GET: UserProfiles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserProfiles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "userId,UserFullName,userAvatar,userGender,userEmail,userOrganization,userPassword")] tblUserProfile tblUserProfile)
        {
            if (ModelState.IsValid)
            {
                tblUserProfile.userId = Guid.NewGuid();
                db.tblUserProfiles.Add(tblUserProfile);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblUserProfile);
        }

        // GET: UserProfiles/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblUserProfile tblUserProfile = db.tblUserProfiles.Find(id);
            if (tblUserProfile == null)
            {
                return HttpNotFound();
            }
            return View(tblUserProfile);
        }

        // POST: UserProfiles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "userId,UserFullName,userAvatar,userGender,userEmail,userOrganization,userPassword")] tblUserProfile tblUserProfile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblUserProfile).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblUserProfile);
        }

        // GET: UserProfiles/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblUserProfile tblUserProfile = db.tblUserProfiles.Find(id);
            if (tblUserProfile == null)
            {
                return HttpNotFound();
            }
            return View(tblUserProfile);
        }

        // POST: UserProfiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            tblUserProfile tblUserProfile = db.tblUserProfiles.Find(id);
            db.tblUserProfiles.Remove(tblUserProfile);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BoardsXpress/BoardsXpress/BoardsXpress/Views/UserManagement/AssignRole.cshtml
@model  BoardsXpress.Models.UserRoleAssignmentViewModels
@{
    ViewBag.Title = "RoleAssignment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>RoleAssignment</h2>
 @using (Html.BeginForm("Roles", "UserManagement", FormMethod.Post))
    {

           <div class="form-group row">
                 @Html.HiddenFor(model=>Model.userDetails.Id)
                       @*@String.Format("{0}  {1} {2}", item.userDetails.FirstName, item.userDetails.MiddleName, item.userDetails.LastName)*@
                   
                </div>

                <div>
                    <table>
                      @foreach (var i in Model.userRole)
                      {
                            <tr>
                                <td>
                                   @Html.RadioButtonFor(m => m.userRoleSelected, i.Value, new { @id = i.Text })
                                   @*@Html.RadioButton("UserRole", i.Value, i.Selected, new { @id = i.Text })*@
                                    @*@Html.RadioButton(item.userDetails.UserName + "userRole", i.groupName, new { @id = i.groupId })*@
                                </td>
                                <td>
                                  @Html.Label(i.Text) 
                                    
                                </td>
                            </tr>
                        }
                    </table>
                    <br />
                                       
                </div>

    
    <input type="submit" value="Submit" />
 }

BoardsXpress/BoardsXpress/BoardsXpress/Views/UserManagement/Create.cshtml
@model BoardsXpress.Models.RegisterViewModel
@{
    ViewBag.Title = "Register";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("Create", "UserManagement", FormMethod.Post, new { enctype = "multipart/form-data" ,@class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>User Details</h4>
        <hr />
        <h3>User Information</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("First Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Middle Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MiddleName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MiddleName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Last Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Email", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.Label("Confrim Email", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.EmailConfirmed)
                        @Html.ValidationMessageFor(model => model.EmailConfirmed, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>*@

        <div class="form-group">
            @Html.Label("Phone number", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>
        @*<div class="form-group">
                @Html.Label("Confrim Phone number", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.PhoneNumberConfirmed)
                        @Html.ValidationMessageFor(model => model.PhoneNumberConfirmed, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>*@
        <div class="form-group">
            @Html.Label("Gender", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Gender,new SelectList(Model.GenderList,"Text","Value"), "Select, please")
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Organisation", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Organisation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Organisation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Designation", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Designation, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Designation, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>


        <hr />
        <h3>User Login Information</h3>
        <hr />

        <div class="form-group">
            @Html.Label("User Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Avatar", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
             @Html.TextBoxFor(Model=> Model.ImageUpload, new { type = "file" })
                @*@Html.EditorFor(model => model.Avatar, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Avatar, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("password", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>

}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BoardsXpress/BoardsXpress/BoardsXpress/Views/UserManagement/Delete.cshtml
@model BoardsXpress.Models.ApplicationUser

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AspNetUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.Label("Full Name")
        </dt>

        <dd>
            @string.Format("{0 },{1},{2}",Model.FirstName,Model.MiddleName,Model.LastName)
        </dd>

        <dt>
            @Html.Label("Email")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)

        <dt>
            @Html.Label("Phone number")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        


    </dl>

    @using (Html.BeginForm("DeleteConfirmed", "UserManagement", FormMethod.Post, new { @class = "form-horizontal", role = "form" })) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model=>model.Id);
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BoardsXpress/BoardsXpress/BoardsXpress/Views/UserManagement/ForgotPassword.cshtml
@model BoardsXpress.Models.ForgotPasswordViewModel
@{
    ViewBag.Title = "Forgot My Password";
    Layout = "~/Views/Shared/_Login.cshtml";
}

<div style="margin-bottom:100px;">
    <div style="text-align:center;margin-top:50px;margin-bottom:-24px;"><img src="~/Media/assets/@Resources.customerLogo" style="height:140px;" /></div><br />
    <div class="login form-module">
        <div class="login-triangle"></div>
        <h4 class="login-header">Reset Password</h4>
        @using (Html.BeginForm("ForgotPassword", "UserManagement", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "login-container", role = "form" }))
            {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.TextBoxFor(model => model.Email, new { @class = "form-control", placeholder = "Enter your email" })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
            <div class="form-group m-5">
                <div>
                    <input type="submit" value="Send a Link to New Password" class="btn btn-default" />
                </div>
            </div>
        }

    </div>
</div>

BoardsXpress/BoardsXpress/BoardsXpress/Views/UserManagement/Login.cshtml
@using BoardsXpress.Models
@model LoginViewModel
@{
    ViewBag.Title = "Log in";
    Layout = "~/Views/Shared/_Login.cshtml";
}

<div style="margin-bottom:100px;">
    <div style="text-align:center;margin-top:50px;margin-bottom:-24px;"><img src="~/Media/assets/@Resources.customerLogo" /></div><br />
    <div class="login form-module">
        <div class="login-triangle"></div>
        <h4 class="login-header">Login</h4>
        @using (Html.BeginForm("Login", "UserManagement", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "login-container", role = "form" }))
            {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.TextBoxFor(m => m.Email, new { placeholder = "Username", @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
            </div>
            <div class="form-group m-5">
                <div>
                    @Html.PasswordFor(m => m.Password, new { placeholder = "Password", @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group m-5">
                <div>
                    <input type="submit" value="Log in" class="btn btn-default" />
                </div>
            </div>

            //Enable this once you have account confirmation enabled for password reset functionality
            <p style="text-align:center;">
                @Html.ActionLink("Forgot your password?", "ForgotPassword")
            </p>
        }

    </div>
</div>