BoardsXpress/BoardsXpress/BoardsXpress/Models/RefDocViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BoardsXpress.Models
{
    public class RefDocViewModel
    {
       public Guid refDocId { get; set;  }
       public string meetingType { get; set; }
       public string refDocName { get; set; }

    }
}

BoardsXpress/BoardsXpress/BoardsXpress/Controllers/RefDocsController.cs
using BoardsXpress.Models;
using BoardsXpress.Repository;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace BoardsXpress.Controllers
{
    [Authorize]

    public class RefDocsController : Controller
    {
        private BoardExpressEntities db = new BoardExpressEntities();
        HelperRepo repo = new HelperRepo();
        // GET: RefDocs
        public ActionResult Index(Guid id)
        {
            var tblRefDocs = db.tblRefDocs.Include(t => t.tblMeetingType).Where(t=>t.meetingTypeId == id);
            repo.meetingIdGlobal = id;
            ViewBag.meetingTypeId = id;
            return View(tblRefDocs.ToList());
        }


        #region SystemGeneratedCodes
        // GET: RefDocs/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblRefDoc tblRefDoc = db.tblRefDocs.Find(id);
            if (tblRefDoc == null)
            {
                return HttpNotFound();
            }
            ViewBag.meetingTypeId = new SelectList(db.tblMeetingTypes, "meetingTypeId", "meetingType", tblRefDoc.meetingTypeId);
            return View(tblRefDoc);
        }

        // POST: RefDocs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "refDocId,meetingTypeId,filePath,fileName,refDocName,htmlContent,publish,webLink")] tblRefDoc tblRefDoc)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblRefDoc).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.meetingTypeId = new SelectList(db.tblMeetingTypes, "meetingTypeId", "meetingType", tblRefDoc.meetingTypeId);
            return View(tblRefDoc);
        }

        // GET: RefDocs/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblRefDoc tblRefDoc = db.tblRefDocs.Find(id);
            if (tblRefDoc == null)
            {
                return HttpNotFound();
            }
            return View(tblRefDoc);
        }

        // POST: RefDocs/Delete/5
        [HttpPost, ActionName("Delete")]
        public JsonResult DeleteConfirmed(Guid id)
        {

            try
            {
                tblRefDoc tblRefDoc = db.tblRefDocs.Find(id);
                db.tblRefDocs.Remove(tblRefDoc);
                db.SaveChanges();
                var result = new { Success = "True", Message = "Success" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex) { }

            var results = new { Success = "False", Message = "Failure" };
            return Json(results, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion

        [HttpPost]
        public JsonResult uploadRefDocument()
        {
            try
            {
                var meetingType = repo.meetingIdGlobal;
                if (Request.Files.Count > 0)
                {
                    var file = Request.Files[0];
                    
                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        var path = Path.Combine(Server.MapPath("~/Documents/referenceDocument"), fileName);
                        if (!Directory.Exists(Server.MapPath("~/Documents/referenceDocument")))
                        {
                            Directory.CreateDirectory(Server.MapPath("~/Documents/referenceDocument"));
                        }
                        file.SaveAs(path);
                        var meetingTypeID = Request.Form["meetingTypeId"];
                        meetingType = Guid.Parse(meetingTypeID);
                        var refDocType = Request.Form["pegionHoleName"];
                        ClsConverter oClsConverter = new ClsConverter();
                        var HtmlContent = oClsConverter.convertDocument(path);
                        if (insertIntoDatabase(fileName, path, refDocType, meetingType, null, HtmlContent))
                        {
                            var results = new { Title = "Message", Message = "Reference Document has been created successfully." };
                            return Json(results, JsonRequestBehavior.AllowGet);
                        }
                    }
                    else
                    {
                        var refDocType = Request.Form["LinkName"];
                        var linkTitle = Request.Form["weblinkTitle"];
                        var meetingTypeID = Request.Form["meetingTypeId"];
                        meetingType = Guid.Parse(meetingTypeID);
                        if (insertIntoDatabase(linkTitle, null, refDocType, meetingType, linkTitle, null))
                        {
                            var results = new { Title = "Message", Message = "Reference Weblink has been created successfully." };
                            return Json(results, JsonRequestBehavior.AllowGet);
                        }
                       
                    }
                }
                else
                {
                    var docType = Request.Form["LinkName"];
                    var meetingTypeId = Request.Form["meetingTypeId"];
                    meetingType = Guid.Parse(meetingTypeId);
                    var linkTitle = Request.Form["weblinkTitle"];
                    if (insertIntoDatabase(linkTitle, null, docType, meetingType, linkTitle, null))
                    {
                        var results = new { Title = "Message", Message = "Reference document uploaded successfully." };
                        return Json(results, JsonRequestBehavior.AllowGet);
                    }
                }
               
            }
            catch (Exception ex)
            {
                var resultant = new { Title = "Message", Message = "Reference document could not be uploaded." };
                return Json(resultant, JsonRequestBehavior.AllowGet);
            }
            var result = new { Title = "Message", Message = "Reference document could not be uploaded." };
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public bool insertIntoDatabase(string fileName, string filePath, string refDocType,Guid meetingType,string webLink = null,string htmlContent = null)
        {
            Guid refDocId = Guid.NewGuid();
            tblRefDoc oRefDocModel = new tblRefDoc()
            {
                refDocId = refDocId,
                fileName = fileName,
                filePath = Path.Combine("/Documents/referenceDocument",fileName),
                refDocName = refDocType,
                publish = false,
                webLink = webLink,
                meetingTypeId = meetingType,
                htmlContent = htmlContent
            };
            try
            {
                db.tblRefDocs.Add(oRefDocModel);
                db.SaveChanges();
                return true;
            }
            catch (Exception ex) { }
            return false;
        }
        public JsonResult publishRefDocs(Guid id)
        {
            tblRefDoc tblRefDoc = db.tblRefDocs.Find(id);
            if (tblRefDoc != null)
            {
                try
                {
                    tblRefDoc.publish = true;
                    db.tblRefDocs.Add(tblRefDoc);
                    db.SaveChanges();
                    var result = new { Success = "True", Message = "Success" };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
                catch(Exception ex) { throw; }
            }

            var results = new { Success = "False", Message = "Failure" };
            return Json(results, JsonRequestBehavior.AllowGet);
        }
        
        public ActionResult getRefNavItem()
        {
            List<RefDocViewModel> RefDocItems = new List<RefDocViewModel>();
            try
            {
                var result = db.tblRefDocs.ToList().OrderBy(x => x.meetingTypeId);
                var meetingTypeDetails = db.tblMeetingTypes;
                if (result != null)
                {
                    foreach (var item in result)
                    {
                        RefDocViewModel refDoc = new RefDocViewModel()
                        {
                            refDocId = item.refDocId,
                            refDocName = item.refDocName,
                            meetingType = meetingTypeDetails.Where(x => x.meetingTypeId == item.meetingTypeId).Select(x => x.meetingType).FirstOrDefault().ToString()
                        };
                        RefDocItems.Add(refDoc);
                    }
                }
            }
            catch (Exception ex) { }
            return View("ReferenceDocuments",RefDocItems);

        }
        [HttpPost]
        public ActionResult loadHtmlData(Guid refDocId)
        {
            try
            {

BoardsXpress/BoardsXpress/BoardsXpress/Views/RefDocs/Index.cshtml
@*@model IEnumerable<BoardsXpress.tblRefDoc>*@

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_DashboardSidebar.cshtml";
    var meetingTypeId = ViewBag.meetingTypeId;
}

<div>
    <span class="btn btn-xs btn-default" data-toggle="tooltip" data-original-title="Takes you to the admin panel" data-placement="top" onclick="location.href = '/MeetingAdministration?id=@meetingTypeId'"><< Go Back to Admin Panel</span>
    <h4 style="text-align:center;">Manage Reference Documents and Resources</h4>
    @*<button class="btn btn-warning pull-right" id="#uploadReferenceModal" data-toggle="modal" data-target="#uploadReferenceModal">Upload</button>*@
    <button class="btn btn-warning pull-right" id="#uploadReferenceModal" data-popup-open="popup-5" href="#" data-toggle="tooltip" data-original-title="Reference document upload" data-placement="bottom">Upload</button>
    <table class="table table-striped" id="sort">
        <thead class="thead-inverse">
            <tr>
                <th style="display:none">ID</th>
                <th>Document Name</th>
                <th>Document Type</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td style="display:none">@item.refDocId</td>
                    @if (!string.IsNullOrEmpty(item.webLink))
                    {
                        <td><a href="@item.fileName" target="_blank">@item.fileName</a></td>
                    }
                    else
                    {
                        <td><a href="@item.filePath">@item.fileName</a></td>
                    }
                    <td>@item.refDocName</td>
                    <td>
                        <span class="glyphicon glyphicon-trash delete" id="#delete" data-toggle="modal" data-target="#deleteModal"></span>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="publish-documents">
        <input type="button" class="btn btn-lg btn-warning" id="publish" value="Publish" style="margin:auto;display:block" data-toggle="modal" data-target="#sucessUploadModal">
    </div>
</div>
<!--Publish Success Modal-->
<div class="modal fade" id="sucessUploadModal" tabindex="-1" role="dialog" aria-labelledby="sucessUploadModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="sucessUploadModal">Message</h4>
            </div>
            <div class="modal-body">
                <p id="successBodyText">Reference Documents Published Successfully.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary successful" id="btnCloseModal">Ok</button>
            </div>
        </div>
    </div>
</div>

<!--Delete Modal-->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="deleteModal">Delete the selected document</h4>
            </div>
            <div class="modal-body">
                <p id="deleteBodyText">Are you sure you want to delete? </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
                <button type="button" class="btn btn-primary" id="deleteRefDoc">Yes</button>
            </div>
        </div>
    </div>
</div>
</br>
</br>

@*Custom modal*@
@*@using (Html.BeginForm("uploadRefDocument", "RefDocs", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {*@
<form class="form" name="refDocUpload" id="refDocUpload">
    <div class="popup" data-popup="popup-5" id="popup-5">
        <div class="popup-inner">
            @*tabs*@
            <ul class="nav nav-tabs" id="tabContent">
                <li class="active"><a href="#upload-refdoc" data-toggle="tab">Upload Reference Document</a></li>
                <li><a href="#upload-reflink" data-toggle="tab">Upload Reference Weblink</a></li>
            </ul>

            @*Upload reference Document*@
            <div class="tab-content">
                <br />
                <div class="tab-pane active" id="upload-refdoc">
                    <div class="form-group row">
                        <label for="message-text" class="col-md-4 col-form-label">Enter Document Name:</label>
                        <div class="col-md-8">
                            <input type="text" class="form-control" id="refInput" name="pegionHoleName" placeholder="Enter name of the document to appear on your reference list." />
                            <input type="hidden" name="meetingTypeId" id="meetingTypeId" value="@meetingTypeId" />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="message-text" class="col-md-4 col-form-label">Upload File:</label>
                        <div class="col-md-8">
                            <input type="file" name="file" id="refUploadFile" multiple autocomplete="off">
                        </div>
                    </div>
                </div>

                @*Upload reference weblink*@
                <div class="tab-pane" id="upload-reflink">
                    <div class="form-group row">
                        <label for="message-text" class="col-md-3 col-form-label">Enter Link Name:</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" name="LinkName" placeholder="Enter name of the link to appear on your reference list." />
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="message-text" class="col-md-3 col-form-label">Insert Link:</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" name="weblinkTitle" placeholder="Insert the link to the site (starting with https://www.)" />
                        </div>
                    </div>
                </div>
            </div>

            @*Action buttons*@
            <div id="custom-modalfooter">
                <!--Progress bar section-->
                <br />
                <div class="progress" style="display:none; margin-top:10px;">
                    <div class="progress-bar progress-bar-striped">Uploading file...</div>
                </div>
                <div id="status"></div>

                <br />
                <button data-popup-close="popup-5" class="btn btn-default pull-left">Cancel</button>
                <button type="submit" class="btn btn-primary pull-right" value="Upload" id="startUpload">Upload</button>
            </div>
            <a class="popup-close" data-popup-close="popup-5" href="#">x</a>
        </div>
    </div>
</form>

@*}*@


<div class="modal fade" id="referenceDocModal" tabindex="-1" role="dialog" data-backdrop="static" aria-labelledby="sucessUploadModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Message</h4>
                </div>
                <div class="modal-body">
                    <p id="referenceDocModalMessage" class="text-center"></p>
                </div>
                <div class="modal-footer">
                    <button type="submit" id="manageDocResponse" data-success="false" class="btn btn-primary successful">Ok</button>
                </div>
            </div>
       
    </div>
</div>
<script src="~/Scripts/Custom/uploadRefDoc.js"></script>
<script>
    $('#btnCloseModal').click(function () {
        $('#sucessUploadModal').modal('hide');
    });
</script>

BoardsXpress/BoardsXpress/BoardsXpress/Views/RefDocs/ReferenceDocuments.cshtml
@model List<BoardsXpress.Models.RefDocViewModel>
@{
    ViewBag.Title = "Reference Documents";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string tempData = string.Empty;
}
@Styles.Render("~/Content/jsTree/themes/default/style.min.css")
<ol class="breadcrumb">
    <li><a href="/home"><span class="glyphicon glyphicon-home"></span></a></li>
    <li><a href="#"><span>Reference Documents and Resources</span></a></li>
</ol>
    <div class="row">
        <div class="col-md-3">
            <div class="well sidebars">
                <ul class="nav nav-list tree">
                    @foreach (var item in Model)
                    {
                        if (tempData != item.meetingType)
                        {
                            <li>@item.meetingType</li>
                            tempData = item.meetingType;
                        }

                        <li><a href="#" onclick="loadHtmlData('@item.refDocId')">@item.refDocName</a></li>
                    }
                </ul>
            </div>
        </div>
        <div class="col-md-9 main-container">
            <div id="HtmlContainer">

            </div>
        </div>
    </div>
    <script>
        function loadHtmlData(refDocId) {
            $.ajax({
                url: '/RefDocs/loadHtmlData',
                type: "POST",
                data: JSON.stringify({ "refDocId": refDocId }),
                contentType: "application/json",
                success: function (result) {
                    if (!result) {
                        return;
                    }

                    if (result.Data.isHtml == true) {
                        $('#HtmlContainer').html(result.Data.msg);
                    }
                    else {
                        if (result.Data.msg.includes('http') == false) {
                            var exists = urlExists('https://' + result.Data.msg);
                            
                            result.Data.msg = ((exists) ? 'https://' : 'http://') + result.Data.msg;
                        }
                        var win = window.open(result.Data.msg, '_blank');
                        win.focus();
                    }
                },
                error: function (error) {

                }
            });
        }

        function urlExists(url, callback) {
            $.ajax({
                type: 'HEAD',
                url: url,
                success: function () {
                    callback(true);
                },
                error: function () {
                    callback(false);
                }
            });
        }
    </script>